version: '3.8'

services:
  ai-article-generator:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL:-https://openrouter.ai/api/v1}
      - OPENAI_MODEL=${OPENAI_MODEL:-openai/gpt-4o-mini}
      - OPENAI_MAX_TOKENS=${OPENAI_MAX_TOKENS:-2500}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE:-0.7}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_TO_FILE=${LOG_TO_FILE:-false}
      - DEFAULT_CONTENT_LENGTH=${DEFAULT_CONTENT_LENGTH:-medium}
      - DEFAULT_TONE=${DEFAULT_TONE:-professional}
      - DEFAULT_SEARCH_DEPTH=${DEFAULT_SEARCH_DEPTH:-10}
      - DEFAULT_RECENCY_HOURS=${DEFAULT_RECENCY_HOURS:-24}
      - DEFAULT_QUALITY_THRESHOLD=${DEFAULT_QUALITY_THRESHOLD:-7.0}
      - DEFAULT_AUTO_OPTIMIZE=${DEFAULT_AUTO_OPTIMIZE:-true}
      - DEFAULT_INCLUDE_ANALYTICS=${DEFAULT_INCLUDE_ANALYTICS:-true}
      - DEFAULT_ARTICLE_COUNT=${DEFAULT_ARTICLE_COUNT:-3}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/v1/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
